### ISSUE TITLE
Game adder

### ISSUE THREAD

**Issue by mrsloth4994** [ItsLogic/Xbox-TitleIDs#1]
Do you have a method to get title IDs to use in the game spoofer?

Also would you ever consider adding the ability to unlock Xbox 360 achievements?

Love the word you do bro💛

**Comment by ItsLogic** [comment]
you can check [this issue](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/issues/14) on the unlocker repo
and no there are no plans for 360 achievements
